In [1]:
import numpy as np
arr = np.array([[6, -8, 73, -110],
                [np.nan, -8, 0, 94]])

# Replace NaN with 0
arr[np.isnan(arr)] = 0

# Interchange rows and columns (without transpose)
rows = len(arr)
cols = len(arr[0])

result = np.array([[arr[i][j] for i in range(rows)] for j in range(cols)])

print(result)

[[   6.    0.]
 [  -8.   -8.]
 [  73.    0.]
 [-110.   94.]]


In [3]:
arr3d = np.arange(24).reshape(2,3,4)

# Move axis 0 to position 2
new_arr = np.moveaxis(arr3d, 0, 2)

print(new_arr.shape)
print(new_arr)

(3, 4, 2)
[[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]


In [2]:
arr = np.array([[1, 2, np.nan],
                [4, np.nan, 6],
                [7, 8, 9]])

# Column means ignoring NaN
col_mean = np.nanmean(arr, axis=0)

# Find NaN positions
inds = np.where(np.isnan(arr))

# Replace NaN with column means
arr[inds] = np.take(col_mean, inds[1])

print(arr)

[[1.  2.  7.5]
 [4.  5.  6. ]
 [7.  8.  9. ]]


In [4]:
arr = np.array([6, -8, 73, -110, 45])

# Replace negative values with 0
arr[arr < 0] = 0

print(arr)

[ 6  0 73  0 45]
